### ISSUE TITLE
Org Babel inline plot

### ISSUE THREAD

**Issue by lccambiaghi** [applied-science/emacs-vega-view#9]
Hi, thank you for this amazing library! I am a beginner with Clojure and Vega-Lite and your project just hit the sweet spot!

I am also a big fan of org mode and use it to produce inline plots with emac-jupyter using the Python and R kernels: https://github.com/dzop/emacs-jupyter. 

I was wondering if you had confidence with this stack and whether you think it would be take a big effort to inline the SVG/PNG produced by Vega into the org document. 

Do you think clojupyter could work out of the box with Oz? I say a neat example here: https://github.com/alanmarazzi/panthera/blob/master/examples/panthera-intro.ipynb

Thank you in advance for your time!

**Comment by lccambiaghi** [comment]
I don't know if you are curious and if it helps but I could plot inline using `ob-clojure` and `clojisr`: https://github.com/lccambiaghi/clojurecast/blob/master/examples/fable.org . Please see the "raw" org file for the header args.

**Comment by jackrusher** [comment]
I'm glad to hear you've found this library helpful! :)

If your goal is to render from literate clojure code, you might want to check out another library of mine called [Darkstar](https://github.com/applied-science/darkstar). You should be able to use it in a very similar way to your `fable.org` example. Check it out and let me know how it goes!

**Comment by lccambiaghi** [comment]
Hi Jack! That is indeed another interesting project to look at! However, I forgot to mention that I would like to avoid writing my specification in JSON but instead to use the EDN used by `vega-view` and `Oz`! 

As I understand it, `vega-view` parses the the EDN spec to JSON before the visualization. Is this conversion implemented also in Darkstar? Thank you!

**Comment by jackrusher** [comment]
@lccambiaghi This got away from me for a few days, sorry. Clojure support requires an active Clojure REPL be connected, which `vega-view` uses to evaluate the form at point before sending the result to Vega. (This works with data literals because they evaluate to themselves.)

You should be able to use a function to convert your spec to JSON (maybe via [data.json](https://github.com/clojure/data.json)) plus a call to Darkstar to get a render-to-file function. Something like:

```clojure
(->> {:your "spec"}
     json/write-str
     darkstar/vega-spec->svg
     (spit "your-file.svg"))
```

I didn't include JSON conversion in Darkstar because different people prefer different JSON libraries and I didn't want to add a possibly superfluous dependency. Let me know if this helps!

**Comment by lccambiaghi** [comment]
Hi Jack, thank you for your comment! I have found a library similar to Darkstar which handles the conversion to JSON and spits out the .png, which I can output in org mode: https://github.com/behrica/vg-cli .

**Comment by jackrusher** [comment]
Glad to hear you found a good solution! :)
